# Generated by Django 5.1 on 2024-08-18 13:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_coupon_booking_activitylog_hotelfaqs_hotelfeatures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
